language: node_js
sudo: false
node_js:
- 8.6.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: T0gXIFaYSxJY3LMBr5XQHOL+i1hKnyLKf6SeSWQvBaJm+BDhGCDCXcpLzaVglKmqSl/gdyBjvSHOxfRMq/6M5AynVpgH5OC19uV8dDbx8bBkH1chTL5G0X0WP1lHEFmLKuxeQem9cS2eR9imYpQX6Ef3VjRR5HpWckOFVtCB2THMu5pmaRdasc0hEspY0Re3WKtgN0Wr8ibrMPupsWMWxi2Wy46/TIGIE4IPfLNp1S+ZuZBwTOTEqQobig7rnbYhOR6f+Yv0DyxhiRQzo9gtMoEI1VjeC/i07ypF/6tBE79EFoHsW1nlm+trtQ6ZuHtmcoonvsQICjK4biQggrOh9htuVDS6xbeuM0ipQqs/ZfiYlBBMsoRlrBnKiBEDu4d80P51m0h4wuLI1ndkFcdtmmdwWXwEtV2rzynyExjlfUZ/Bpx5ElrYYS6jX7miuDV8EUR53XsURMDBnQiD9OMkyBb5FS7sX8zHSF45f/R6lAsDGXNkDFntePM4OZEvic3/s0pCdfhGsw6FpdKVrsIdvZhQg80DU8zjz1TW4GJFdCvggHnCoTukiRFP9iUAzjwdkObsBdLBrh3kWFwKyZMTka1LRT9GNQEVwYIadoi3szXK/ubPuRdMUo+7e1zdD+O/bGlXzYqjLekvUr2JpfblP5ZDt62cfj9uxJIbdoJfvXE=
before_install:
- npm install -g coveralls pr-bumper@^3.7.0 ciena-devops@^1.0.0
- "$(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh"
install:
- "$(npm root -g)/pr-bumper/.travis/maybe-install.sh"
script:
- "$(npm root -g)/pr-bumper/.travis/maybe-test.sh"
- "$(npm root -g)/pr-bumper/.travis/maybe-bump-version.sh"
after_success:
- "$(npm root -g)/pr-bumper/.travis/maybe-publish-coverage.sh"
after_deploy:
- "$(npm root -g)/ciena-devops/scripts/slack/incoming-webhooks/send-message.sh"
deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: fKzjNZSgK0A2ANhHaP2mWKjyaXFWUiMHIziyxhGpTwRk37uNblco7j+/5CzVk+brjfRlebLVK3FKfPDzbrxv7XLvWh0KYf6Qm5aLCYUtMWZn6zbqDaVzxjDztI6argrflzPEhqptZ+kHU/iv05hWcfhcmuArMZhp9Cu8HMxhhAsXq/yILaOP4tkQa5RCKxWQeVYqa2nTmd+5OxDsIxkNXytPYyMuR834sBjKFEo055/xFCTry7NOv2vhyokb+2EIV06QinLUXkNVmuAOOYSH6OXOEsDQo3lNstJpGROltPDhKqjGO9cHO35cz2n172+OVhFvZ3eTEjRJwVSk36RN7VOTQJmTUERjt79NitSGe7HtAeNmmBM9VHTezWjSMzhZ21npRWOdowa0m72XdepZbduuuG8C7VeOG4lh9nOJka/CHGx9Unmc7KcG+RhrDrmb5ruJicyHWOrB1LNT9tQlTdu++d+K3EQAiD8efaUMDZCdbaugxQLqNVWldsYFh0B0/Ag222PLxRrZ46exhvuBhTNHl0lyA+s968nQ+Dw0cYVpz8lxaM2pqKZHKcKp/nFMss3vZOCycwib3zsP3aAMgWpoWdUa6F13PwTyu5lXlBR7AT4hxH8nlG8n0DROXuSE7r9SD8EDjQoxnidoUcyL8hRtV/WWjPpb4E+pho8Xlx0=
  on:
    all_branches: true
    node: 8.6.0
    tags: true
notifications:
  slack:
    secure: nqB8jLh17djxUC1TZ8T+0tUr9fpSczPBWvgkjCB52iFsyfMbCq7zvQr11VdIU7AI8BD0dpGk0pKvJhTju+tjGerWmV6tH5V9c5qbphlzZcCyCGA416mV3hwKEj2JVo8FxZJzBt7S3AtaEYHdEKUfqKtQcmLwXKqg8otfG92v2MvNHWQJ6K0FKndnEJhxIri0e2N8YUPgK/i5gFzI5dABUX5Kc1Zguo21PDK9wey3ZePHuu2kz2L8nxRYUgcM/uI95QbPJqoQHXS6AnpTVe8Zergryb21AAIvUS1NOakQrfuAbNPVwwSsZmxWg9sQD5ztYuKuUt2BoH9xiClYucK3sCGTkgcqhffKy+/jgr6CEdBpJS5Qhtz4xskW/aYzclPjjLIc5ZcxKuXMM8MEQaZalpriuAHhJDA8F4lIcGS2C1OyBiEbWicxJWLSjEQ2vkfkyLvVYWC1cVN2j66HtyzgCZ0YYf73K9b6ofOOIjL3uIVCQghBgttomqgEtkmjpp4yP7vSc78iTHB1nHMhhPqeHbWTgpWdyH+BADl3cUBKQFah0KuVnD/izR7TdSXkqJGWvwtXkv7zp4bth7fMKcP8260xFyKdy0SAzgRKjdVdtqGnk+d15jmWNnjWd6U5ipXHc26HxsoSqc5zPw7XIMR+w0DNgHtUa40lXlEcwck8nCw=
