language: node_js
sudo: false
node_js:
  - '5.3'

before_install:
  - npm install -g coveralls

after_success:
  - cat coverage/lcov.info | coveralls

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - CXX=g++-4.8

before_deploy:
  - ./scripts/git-tag.sh

deploy:
  provider: npm
  email: adam.meadows@gmail.com
  api_key:
    secure: R5AwlhH2CfcjT7b3CM15gH2Fg+zJg8o7Gq1WZP4QGlEW9ID/yXU8lg/kFCaFkwq8pchIAvL6O4KwWOreo59IiNKeW3fIr2IgqBS4pHbfnow1ZI/YoPb/jy4CEBc5YWR9upFJCLYnwglh+Cu+uFGe6EiMI6aBpHmm9gZUXi3LgnGZvCu2hBbhjZdu0MJm19jRbrOFUXcF30E1LhLBtvspecm1SckESTgfIjK2B9guC5/P+p8AAkUcAEVx5sZNrTIwRNPFsKLJORbFG73huq/kkiQXHUYalp3JNzqrKVFAGJkp4rl2lYGRn85UxPgGyLwdWjdEF4kWiFtEKjddiz0yP5KerPmBMKf/Kwipup4LGnX5mccVNtGxFKcQIlw2M+W4EgnM+WverB8cJEji8ng9uE5xTZ/hv3YHwv5YvwLrtxXqReASO+nrQxcPmGmd9/DdmJJhSZws63lCYZzABfl5uBJHx9elGCZSUvxmgX4A8+lrbSePpcy58YmtAxyBaUjULlDg6wKy+nH62HHQLjYCeXZs7jEtXr9QBp5veVUnrSXSGG2fQ1O4JK1WkYnU0B10+eR1Hj4d1v+R1eH21bLXBPFcYWDW2LXZxaYT32DEZKp1dTymVSgrDJNAphmMpqNwT8SmNC7v3K9nte8C81xqV+dPaMC6Tc1AjOJzkNtRE5M=
