language: node_js
sudo: false
node_js:
  - '5.3'

before_install:
  - npm install -g coveralls

after_success:
  - cat coverage/lcov.info | coveralls

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  matrix:
    - CXX=g++-4.8
  global:
    secure: rKofjfa4BJqo244CeT8lMrC7br9uL4L/c3gz4iFTh8ArKZ8lcF7Nv0RWiZrIFMs9muKF5zEW0hLdp+XYK4ajOmgqjlc7HeIqQDuDsDMB1w3tfTUBxdtgeK3aLlaKpzKvcxDiWtN2S6attXgEGZOTSwxLKTYCVVwbdbB1ZMSYeGKgxM2+QPxME2A7cl+Um76U03TBXeYzsrO0lLdN2JPrkVocL0MwOZj6e4SP88RkX2o5tgI3qkKj6qoeXvT7JqT1w42DMvXunCTvH0MeYkT2snVJ7K5XUedi3kTO5UIkH51R8Mlo4Y6rXi8R4vyG5zL26GVNF4igQr74pv0Skfghwe9Q2w+zzWadjYsvXZOhiU9OOhaS9qvK0djFYuAXNecBDEK1Q3L5N/C0fe60sxPz8OuQYs/koyNkbfWgwYrLK29pC0dA+lGV+fnBpx2txqM8V6HcGBVjm1Uhunkd6DKlFF7Zq5PgMrf0W4qBKFWo3xshkD6k+k6Gbi5WSEUCgxes+a9uKIBi62U4Dvz0uDUiwNIp9DEDL8nXsoU4Avi8f3JWvAdl2GpY06yQYtmFrHRPEMN0TAOaoFt/eT/D+pOyc/q0vfcMT92qAdCL5mL3aOy0x0QiHYcNO+iQjVcTIbNGbv0mHF/BDVZdNQLoz72Zg/ynHk0E2hqiGto7k54rJkE=

before_deploy:
  - ./scripts/git-tag.sh

deploy:
  provider: npm
  email: adam.meadows@gmail.com
  api_key:
    secure: aA/XIIWTozJ/gDHbvsJaHdDr2mH7Nc5dts5eD6sqX5LMyNgbeZpbF7tHmjHa/1SrifBzvuNWzMR1qZPlZjnW2J1Vys06FToQEiwUIHnWPJfy1emuQjpQL9JtTtYT4XP72+6sQDTA7EwkdQCjZSP6g5e9XfIBMae2BW2y2R83Cp7uY9+FZwlwvJ/cbbmXxetFMNPrI3DA3Pw9EeKNJ6edvBqvKBIwIdIdXF8bWZOzlM/lkzJ+mnLa9W3m7Qqp56Gps+MUswfYjUIRpZETH1O4f2n+RDePaswqYgHzEaPGkv/gUg6UtLT9WDIiW6yM/JMG0TgFgJ7c4eIT50fnGfw0YQUrlJ2nw07eT0s82Fh475dndsyp8GOmAgRSTZ3NBXYtrR3jEYwjgyTLJLXWT+6psvlpNWF4EGMs+//XgKCjw6vfBpr+h3yVoWoKbhKViqimw2XiagePHNfkoDAN2009ASyqflaaBkIllQaNFe96V2riGZg5aFCJLJpbipZTMULQ/cucm3wYn0ZrIHw7rK8K3/TohEtunic0bDkidZEJXm4CHnk9Vv6nVAP5IAgbHFTYzwe5Uua48thrwz+OQZ/EZcz+80DeppXP7oP794HnHwexFvFkL01mQcKl9SPPV0Y4u6VMxBZesyFXYCz/ENwJxjryQK4IKHTpP5mn2keA5E8=
  on:
    branch: master
    tags: false
